//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdagendaEntities : DbContext
    {
        public bdagendaEntities()
            : base("name=bdagendaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbagenda> tbagenda { get; set; }
        public DbSet<tbarchivo> tbarchivo { get; set; }
        public DbSet<tbnotas> tbnotas { get; set; }
        public DbSet<tbpersona> tbpersona { get; set; }
        public DbSet<tbusuario> tbusuario { get; set; }
    }
}
