//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbagenda
    {
        public tbagenda()
        {
            this.tbnotas = new HashSet<tbnotas>();
        }
    
        public int cod_agenda { get; set; }
        public Nullable<int> cod_usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual tbusuario tbusuario { get; set; }
        public virtual ICollection<tbnotas> tbnotas { get; set; }
    }
}
