//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbnotas
    {
        public tbnotas()
        {
            this.tbarchivo = new HashSet<tbarchivo>();
        }
    
        public int cod_notas { get; set; }
        public Nullable<int> cod_agenda { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual tbagenda tbagenda { get; set; }
        public virtual ICollection<tbarchivo> tbarchivo { get; set; }
    }
}
