//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbusuario
    {
        public tbusuario()
        {
            this.tbagenda = new HashSet<tbagenda>();
        }
    
        public int cod_usuario { get; set; }
        public Nullable<int> cod_persona { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual ICollection<tbagenda> tbagenda { get; set; }
        public virtual tbpersona tbpersona { get; set; }
    }
}
